-- DROP TABLES

DROP TABLE producto_envio;
DROP TABLE PRODUCTO;
DROP TABLE VALORACION;
DROP TABLE REGISTRO;
DROP TABLE LUGAR_ACUERDO;
DROP TABLE SUCURSAL_ASIGNADA;
DROP TABLE ENVIO;
DROP TABLE SUCURSAL;
DROP TABLE DIRECCION;
DROP TABLE UNIDAD;
DROP TABLE USUARIO;
DROP TABLE SEDE;
DROP TABLE ACUERDO_SERVICIO;
DROP TABLE SERVICIO;
DROP TABLE CALLE;
DROP TABLE MUNICIPIO;
DROP TABLE ESTADO;
DROP TABLE aliado_comercial;
DROP TABLE proveedor;



--DROP TDA BODY

DROP TYPE BODY datos_basicos;
DROP TYPE BODY HISTORICO;
DROP TYPE BODY DATOS_LUGAR;

--DROP TDA OBJECT

DROP TYPE datos_basicos;
DROP TYPE HISTORICO;
DROP TYPE DATOS_LUGAR;